### ISSUE TITLE
Compiler crashes when setting a global variable inside a let, lambda, or define form

### ISSUE THREAD

**Issue by abbrev** [stamourv/picobit#4]
Compiler crashes when setting a global variable inside a let, lambda, or define form.

    (define *x* 0)
    
    ; Any one of the following crashes the picobit compiler:
    
    (let ((x 1)) (set! *x* x))
    
    ((lambda () (set! *x* 1)))
    
    (define (picobit-crashes) (set! *x* 1))
    (picobit-crashes)

Expected: \*x* is set to 1

Actual results: compiler crashes with the following message:

    $ ./picobit picobit-set-fail.scm
    ref-var: contract violation
      expected: ref?
      given: #0=(set #f (list (ref #0# '() ...)) ...)
      context...:
       /home/c/arduino-picobit/compiler/ast.rkt:91:0: discard-node!
       /home/c/arduino-picobit/compiler/ast.rkt:91:0: discard-node!
       /home/c/arduino-picobit/compiler/ast.rkt:112:0: substitute-child!
       loop
       /home/c/arduino-picobit/compiler/picobit.rkt: [running body]

Similar forms compile and work as expected:

    (define *x* 0)
    
    (let ((x 1)) (set!  x  x ))
    
    (let ((x 1)) (set!  x *x*))
    
    (let (     ) (set! *x* 1 ))

I'm working from your latest master branch (commit 068e348d036928382b842e3fa9b68da3a7a44b0b).

Other information that might be helpful:

    $ racket --version
    Welcome to Racket v6.2.
    $ uname -a
    Linux mars 2.6.32-5-686 #1 SMP Tue May 13 16:33:32 UTC 2014 i686 GNU/Linux
    $ cat /etc/debian_version
    8.0

**Comment by stamourv** [comment]
Fixed, thanks for the report!
